version: '3.9'

services:
  crawl4ai-service:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./logs:/logs 
    environment:
      - DATA_DIR=/data
      - LOG_DIR=/logs
